import type { Menu, Restaurant } from './types'

/**
 * Fallback demo data. The real API (menupro.ci) is the source of truth, but in
 * environments where it can't be reached (CORS / offline preview) we fall back
 * to this so the interface is never blank. Prices are in centimes XOF.
 */
export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 1,
    name: 'Maquis Le Bon Coin',
    slug: 'maquis-le-bon-coin',
    category: 'restaurant',
    city: 'Abidjan',
    address: 'Cocody Angré, 7ème tranche',
    phone: '0709123456',
    logo_url: '/images/banner-maquis.png',
    banner_url: '/images/banner-maquis.png',
    is_open: true,
    min_order_amount: 0,
    avg_prep_time: 20,
    latitude: '5.3812',
    longitude: '-3.9561',
    distance_km: 2.3,
    delivery_fee: 77000,
    opening_hours: 'Lun-Dim · 10h00 - 23h00',
  },
  {
    id: 2,
    name: 'Chez Tante Adjoua',
    slug: 'chez-tante-adjoua',
    category: 'grillades',
    city: 'Abidjan',
    address: 'Marcory Zone 4',
    phone: '0708223344',
    logo_url: '/images/banner-poulet.png',
    banner_url: '/images/banner-poulet.png',
    is_open: true,
    min_order_amount: 200000,
    avg_prep_time: 25,
    latitude: '5.3092',
    longitude: '-3.9891',
    distance_km: 0.8,
    delivery_fee: 50000,
    opening_hours: 'Lun-Sam · 11h00 - 22h00',
  },
  {
    id: 3,
    name: 'Pizza Napoli Abidjan',
    slug: 'pizza-napoli',
    category: 'pizza',
    city: 'Abidjan',
    address: 'Plateau, Avenue Chardy',
    phone: '0501778899',
    logo_url: '/images/banner-pizza.png',
    banner_url: '/images/banner-pizza.png',
    is_open: true,
    min_order_amount: 300000,
    avg_prep_time: 30,
    latitude: '5.3252',
    longitude: '-4.0189',
    distance_km: 4.1,
    delivery_fee: 120000,
    opening_hours: 'Lun-Dim · 11h30 - 23h30',
  },
  {
    id: 4,
    name: 'Burger Time',
    slug: 'burger-time',
    category: 'fast_food',
    city: 'Abidjan',
    address: 'Yopougon Selmer',
    phone: '0700556677',
    logo_url: '/images/banner-fastfood.png',
    banner_url: '/images/banner-fastfood.png',
    is_open: false,
    min_order_amount: 150000,
    avg_prep_time: 15,
    latitude: '5.3376',
    longitude: '-4.0812',
    distance_km: 6.7,
    delivery_fee: 150000,
    opening_hours: 'Lun-Dim · 12h00 - 00h00',
  },
  {
    id: 5,
    name: 'Garba Express',
    slug: 'garba-express',
    category: 'fast_food',
    city: 'Bouaké',
    address: 'Bouaké Commerce',
    phone: '0505443322',
    logo_url: '/images/banner-maquis.png',
    banner_url: '/images/banner-maquis.png',
    is_open: true,
    min_order_amount: 0,
    avg_prep_time: 10,
    latitude: '7.6906',
    longitude: '-5.0304',
    distance_km: 1.5,
    delivery_fee: 40000,
    opening_hours: 'Lun-Dim · 09h00 - 21h00',
  },
]

const MENU_1: Menu = {
  restaurant_id: 1,
  currency: 'XOF',
  categories: [
    {
      id: 1,
      name: 'Plats principaux',
      dishes: [
        {
          id: 10,
          name: 'Attiéké poisson braisé',
          description: 'Attiéké frais accompagné de poisson braisé et sauce tomate',
          price: 300000,
          compare_price: null,
          image_url: '/images/dish-attieke.png',
          is_available: true,
          is_featured: true,
          is_spicy: false,
          is_vegetarian: false,
          prep_time: 15,
          calories: null,
        },
        {
          id: 11,
          name: 'Poulet braisé + attiéké',
          description: 'Demi-poulet braisé mariné, attiéké et oignons grillés',
          price: 450000,
          compare_price: 500000,
          image_url: '/images/dish-poulet.png',
          is_available: true,
          is_featured: true,
          is_spicy: true,
          is_vegetarian: false,
          prep_time: 20,
          calories: null,
        },
        {
          id: 12,
          name: 'Garba spécial',
          description: 'Attiéké, thon frit, tomate, oignon et piment',
          price: 150000,
          compare_price: null,
          image_url: '/images/dish-garba.png',
          is_available: false,
          is_featured: false,
          is_spicy: true,
          is_vegetarian: false,
          prep_time: 10,
          calories: null,
        },
      ],
    },
    {
      id: 2,
      name: 'Accompagnements',
      dishes: [
        {
          id: 13,
          name: 'Alloco',
          description: 'Bananes plantains frites, sauce tomate pimentée',
          price: 100000,
          compare_price: null,
          image_url: '/images/dish-alloco.png',
          is_available: true,
          is_featured: false,
          is_spicy: false,
          is_vegetarian: true,
          prep_time: 8,
          calories: null,
        },
      ],
    },
    {
      id: 3,
      name: 'Boissons',
      dishes: [
        {
          id: 14,
          name: 'Jus de bissap / gingembre',
          description: 'Jus naturel maison bien frais',
          price: 50000,
          compare_price: null,
          image_url: '/images/dish-jus.png',
          is_available: true,
          is_featured: false,
          is_spicy: false,
          is_vegetarian: true,
          prep_time: 2,
          calories: null,
        },
      ],
    },
  ],
}

const MENU_PIZZA: Menu = {
  restaurant_id: 3,
  currency: 'XOF',
  categories: [
    {
      id: 20,
      name: 'Pizzas',
      dishes: [
        {
          id: 30,
          name: 'Pizza Margherita',
          description: 'Sauce tomate, mozzarella, basilic frais',
          price: 550000,
          compare_price: null,
          image_url: '/images/dish-pizza.png',
          is_available: true,
          is_featured: true,
          is_spicy: false,
          is_vegetarian: true,
          prep_time: 18,
          calories: null,
        },
      ],
    },
    {
      id: 21,
      name: 'Boissons',
      dishes: [
        {
          id: 31,
          name: 'Jus de bissap / gingembre',
          description: 'Jus naturel maison bien frais',
          price: 50000,
          compare_price: null,
          image_url: '/images/dish-jus.png',
          is_available: true,
          is_featured: false,
          is_spicy: false,
          is_vegetarian: true,
          prep_time: 2,
          calories: null,
        },
      ],
    },
  ],
}

export function mockMenu(restaurantId: number): Menu {
  if (restaurantId === 3) return { ...MENU_PIZZA, restaurant_id: restaurantId }
  return { ...MENU_1, restaurant_id: restaurantId }
}

export function mockRestaurant(id: number): Restaurant {
  return MOCK_RESTAURANTS.find((r) => r.id === id) ?? MOCK_RESTAURANTS[0]
}
